/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ec.telas;

import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        menuCad = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menCadUsuarios = new javax.swing.JMenuItem();
        menuCadClientes = new javax.swing.JMenuItem();
        menuCadFornecedor = new javax.swing.JMenuItem();
        menuVen = new javax.swing.JMenu();
        MenuCardVendas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuOpcSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Estoque Controle");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("Usuário");

        lblUsuario.setText("jLabel2");

        lblData.setText("Data");

        menuCad.setText("Cadastro");
        menuCad.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jMenuItem1.setText("Produtos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuCad.add(jMenuItem1);

        menCadUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        menCadUsuarios.setText("Usuários");
        menCadUsuarios.setEnabled(false);
        menCadUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadUsuariosActionPerformed(evt);
            }
        });
        menuCad.add(menCadUsuarios);

        menuCadClientes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        menuCadClientes.setText("Clientes");
        menuCadClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadClientesActionPerformed(evt);
            }
        });
        menuCad.add(menuCadClientes);

        menuCadFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        menuCadFornecedor.setText("Fornecedor");
        menuCadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadFornecedorActionPerformed(evt);
            }
        });
        menuCad.add(menuCadFornecedor);

        menu.add(menuCad);

        menuVen.setText("Vendas");
        menuVen.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        MenuCardVendas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        MenuCardVendas.setText("Criar Venda");
        MenuCardVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCardVendasActionPerformed(evt);
            }
        });
        menuVen.add(MenuCardVendas);

        menu.add(menuVen);

        jMenu4.setText("Opções");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        menuOpcSair.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        menuOpcSair.setText("Sair");
        menuOpcSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOpcSairActionPerformed(evt);
            }
        });
        jMenu4.add(menuOpcSair);

        menu.add(jMenu4);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(lblUsuario)
                .addGap(225, 225, 225)
                .addComponent(lblData)
                .addContainerGap(574, Short.MAX_VALUE))
            .addComponent(Desktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Desktop, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblUsuario)
                    .addComponent(lblData)))
        );

        setSize(new java.awt.Dimension(946, 694));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
        Date data = new Date();
        DateFormat formataData = DateFormat.getDateInstance(DateFormat.SHORT);
        lblData.setText(formataData.format(data));
    }//GEN-LAST:event_formWindowActivated

    private void menuOpcSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOpcSairActionPerformed
        
        int sair = JOptionPane.showConfirmDialog(null,"Te certeza que deseja sair? ", "Atenção",JOptionPane.YES_NO_OPTION);
        System.out.println(sair);
        if (sair==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_menuOpcSairActionPerformed

    private void menCadUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadUsuariosActionPerformed
        TelaUsuario usuario = new TelaUsuario();
        usuario.setVisible(true);
        Desktop.add(usuario);
    }//GEN-LAST:event_menCadUsuariosActionPerformed

    private void menuCadClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadClientesActionPerformed
        TelaCliente cliente = new  TelaCliente();
        cliente.setVisible(true);
        Desktop.add(cliente);
    }//GEN-LAST:event_menuCadClientesActionPerformed

    private void menuCadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadFornecedorActionPerformed
       TelaFornecedor fornecedor = new  TelaFornecedor();
        fornecedor.setVisible(true);
        Desktop.add(fornecedor);
    }//GEN-LAST:event_menuCadFornecedorActionPerformed

    private void MenuCardVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCardVendasActionPerformed
   TelaVendas venda = new  TelaVendas();
        venda.setVisible(true);
        Desktop.add(venda);        // TODO add your handling code here:
    }//GEN-LAST:event_MenuCardVendasActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       TelaProduto produto = new  TelaProduto();
        produto.setVisible(true);
        Desktop.add(produto);  // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuItem MenuCardVendas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblData;
    public static javax.swing.JLabel lblUsuario;
    public static javax.swing.JMenuItem menCadUsuarios;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu menuCad;
    private javax.swing.JMenuItem menuCadClientes;
    private javax.swing.JMenuItem menuCadFornecedor;
    private javax.swing.JMenuItem menuOpcSair;
    private javax.swing.JMenu menuVen;
    // End of variables declaration//GEN-END:variables
}
